export type PhoneLengthRule = { min: number; max: number };

export const DEFAULT_PHONE_LENGTH_RULE: PhoneLengthRule = { min: 7, max: 11 };

/** 各国/地区手机号（不含区号）有效位数 */
export const PHONE_NATIONAL_LENGTH_RULES: Record<string, PhoneLengthRule> = {
  CN: { min: 11, max: 11 },
  AF: { min: 9, max: 9 },
  AL: { min: 9, max: 9 },
  DZ: { min: 9, max: 9 },
  AD: { min: 6, max: 6 },
  AO: { min: 9, max: 9 },
  AR: { min: 10, max: 10 },
  AM: { min: 8, max: 8 },
  AU: { min: 9, max: 9 },
  AT: { min: 10, max: 10 },
  AZ: { min: 9, max: 9 },
  BH: { min: 8, max: 8 },
  BD: { min: 10, max: 10 },
  BY: { min: 9, max: 9 },
  BE: { min: 9, max: 9 },
  BZ: { min: 7, max: 11 },
  BJ: { min: 8, max: 8 },
  BO: { min: 8, max: 8 },
  BA: { min: 8, max: 8 },
  BW: { min: 7, max: 11 },
  BR: { min: 10, max: 11 },
  BN: { min: 7, max: 7 },
  BG: { min: 9, max: 9 },
  BF: { min: 8, max: 8 },
  KH: { min: 8, max: 8 },
  CM: { min: 9, max: 9 },
  CA: { min: 10, max: 10 },
  CV: { min: 7, max: 7 },
  CF: { min: 8, max: 8 },
  TD: { min: 8, max: 8 },
  CL: { min: 9, max: 9 },
  CO: { min: 10, max: 10 },
  CG: { min: 9, max: 9 },
  CR: { min: 8, max: 8 },
  HR: { min: 9, max: 9 },
  CU: { min: 8, max: 8 },
  CY: { min: 8, max: 8 },
  CZ: { min: 9, max: 9 },
  DK: { min: 8, max: 8 },
  DO: { min: 10, max: 10 },
  EC: { min: 9, max: 9 },
  EG: { min: 10, max: 10 },
  SV: { min: 8, max: 8 },
  EE: { min: 8, max: 8 },
  ET: { min: 9, max: 9 },
  FI: { min: 9, max: 9 },
  FR: { min: 9, max: 9 },
  GA: { min: 8, max: 8 },
  GE: { min: 9, max: 9 },
  DE: { min: 10, max: 10 },
  GH: { min: 9, max: 9 },
  GR: { min: 10, max: 10 },
  GT: { min: 8, max: 8 },
  HN: { min: 8, max: 8 },
  HK: { min: 8, max: 8 },
  HU: { min: 9, max: 9 },
  IS: { min: 7, max: 7 },
  IN: { min: 10, max: 10 },
  ID: { min: 9, max: 11 },
  IR: { min: 10, max: 10 },
  IQ: { min: 10, max: 10 },
  IE: { min: 9, max: 9 },
  IL: { min: 9, max: 9 },
  IT: { min: 10, max: 10 },
  CI: { min: 10, max: 10 },
  JM: { min: 10, max: 10 },
  JP: { min: 10, max: 10 },
  JO: { min: 9, max: 9 },
  KZ: { min: 10, max: 10 },
  KE: { min: 9, max: 9 },
  KW: { min: 8, max: 8 },
  KG: { min: 7, max: 11 },
  LA: { min: 9, max: 9 },
  LV: { min: 8, max: 8 },
  LB: { min: 8, max: 8 },
  LY: { min: 9, max: 9 },
  LT: { min: 8, max: 8 },
  LU: { min: 9, max: 9 },
  MO: { min: 8, max: 8 },
  MG: { min: 9, max: 9 },
  MY: { min: 9, max: 10 },
  MV: { min: 7, max: 11 },
  MT: { min: 8, max: 8 },
  MX: { min: 10, max: 10 },
  MD: { min: 7, max: 11 },
  MC: { min: 8, max: 8 },
  MN: { min: 8, max: 8 },
  ME: { min: 8, max: 8 },
  MA: { min: 9, max: 9 },
  MZ: { min: 9, max: 9 },
  MM: { min: 8, max: 10 },
  NP: { min: 10, max: 10 },
  NL: { min: 9, max: 9 },
  NZ: { min: 8, max: 10 },
  NI: { min: 8, max: 8 },
  NE: { min: 8, max: 8 },
  NG: { min: 10, max: 10 },
  MK: { min: 8, max: 8 },
  NO: { min: 8, max: 8 },
  OM: { min: 8, max: 8 },
  PK: { min: 10, max: 10 },
  PA: { min: 8, max: 8 },
  PY: { min: 9, max: 9 },
  PE: { min: 9, max: 9 },
  PH: { min: 10, max: 10 },
  PL: { min: 9, max: 9 },
  PT: { min: 9, max: 9 },
  PR: { min: 10, max: 10 },
  QA: { min: 8, max: 8 },
  RO: { min: 9, max: 9 },
  RU: { min: 10, max: 10 },
  RW: { min: 9, max: 9 },
  SA: { min: 9, max: 9 },
  SN: { min: 9, max: 9 },
  RS: { min: 9, max: 9 },
  SG: { min: 8, max: 8 },
  SK: { min: 9, max: 9 },
  SI: { min: 8, max: 8 },
  ZA: { min: 9, max: 9 },
  KR: { min: 10, max: 10 },
  ES: { min: 9, max: 9 },
  LK: { min: 9, max: 9 },
  SD: { min: 9, max: 9 },
  SE: { min: 9, max: 9 },
  CH: { min: 9, max: 9 },
  SY: { min: 9, max: 9 },
  TW: { min: 9, max: 9 },
  TZ: { min: 9, max: 9 },
  TH: { min: 9, max: 9 },
  TN: { min: 8, max: 8 },
  TR: { min: 10, max: 10 },
  UG: { min: 9, max: 9 },
  UA: { min: 9, max: 9 },
  AE: { min: 9, max: 9 },
  GB: { min: 10, max: 10 },
  US: { min: 10, max: 10 },
  UY: { min: 8, max: 8 },
  UZ: { min: 9, max: 9 },
  VE: { min: 10, max: 10 },
  VN: { min: 9, max: 9 },
  YE: { min: 9, max: 9 },
  ZM: { min: 9, max: 9 },
  ZW: { min: 9, max: 9 },
};

export function getPhoneLengthRule(countryId: string): PhoneLengthRule {
  return PHONE_NATIONAL_LENGTH_RULES[countryId] ?? DEFAULT_PHONE_LENGTH_RULE;
}

export function nationalPhoneDigits(raw: string): string {
  return raw.replace(/\D/g, '');
}

export function isValidNationalPhoneLength(countryId: string, raw: string): boolean {
  const len = nationalPhoneDigits(raw).length;
  if (len === 0) return false;
  const { min, max } = getPhoneLengthRule(countryId);
  return len >= min && len <= max;
}
